# Generated by Django 2.1.7 on 2019-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_about_manager', models.ImageField(help_text='width_field=500, height_field=535', upload_to='about_manager')),
                ('name', models.CharField(max_length=20)),
                ('paragraphe', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='About_porfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_porfolio_1', models.ImageField(blank=True, help_text='width_field=900, height_field=632', upload_to='image_about_porfolio')),
                ('image_porfolio_2', models.ImageField(blank=True, help_text='width_field=900, height_field=632', upload_to='image_about_porfolio')),
                ('image_porfolio_3', models.ImageField(blank=True, help_text='width_field=900, height_field=632', upload_to='image_about_porfolio')),
            ],
        ),
        migrations.CreateModel(
            name='About_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(blank=True, max_length=300)),
                ('text_2', models.CharField(blank=True, max_length=300)),
                ('text_3', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logo_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField(blank=True, help_text='lien')),
                ('image_logo', models.ImageField(blank=True, help_text='width_field=310, height_field=120', upload_to='logo_client')),
            ],
        ),
        migrations.CreateModel(
            name='Manager_say',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('paragraphe', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_present_1', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_2', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_3', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_4', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_5', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_6', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_7', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('image_present_8', models.ImageField(blank=True, help_text='width_field=870, height_field=350', upload_to='presentation')),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('paragraphe', models.CharField(blank=True, max_length=350)),
                ('category', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('text_entrepise', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recent_Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_title', models.ImageField(blank=True, help_text=' width_field=900, height_field=632', upload_to='recent_travail')),
                ('image_travail', models.ImageField(blank=True, help_text='width_field=900, height_field=632', upload_to='recent_travail')),
                ('paragraphe', models.CharField(max_length=50)),
            ],
        ),
    ]
